micronaut:
  application:
    name: zoomchart
  server:
    netty:
      responses:
        file:
          cache-seconds: 900
          cache-control:
            public: true
    port: 8080
  router:
    static-resources:
      default:
        mapping: "/**"
        paths: ["classpath:static"]